language: node_js
node_js:
- '0.12'
- '0.10'
before_install:
- openssl aes-256-cbc -K $encrypted_82d675aae8ba_key -iv $encrypted_82d675aae8ba_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 400 ~/.ssh/id_rsa
- npm config set spin false
- npm install -g bower
- npm install -g mocha
install:
- npm install
- cd client && npm install && bower install
- cd ../server && npm install
- cd ..
cache:
  directories:
  - ~/conference-room/node_modules
  - ~/conference-room/client/node_modules
  - ~/conference-room/server/node_modules
  - ~/conference-room/client/bower_components
after_success:
- ssh refvemw@0.tcp.ngrok.io -o StrictHostKeyChecking=no -p 43793 'cd /u01/conference-room && git pull'

notifications:
  slack:
    secure: di870+2Ue/U5CZud2UOG7k/yByYi5q9G7UOQneJFy+tq4SncXLexJn9yqw9VpgZ6H/8dFEJ/49HgFY0/Ntx+5WaBO3sGNWen+uPBPY2NVmN6Pfsox3lUJRy53jtFjQk9aHBIJVew6Fh6IUoWLP/Dk1MjDQqAVH0KSBL5lQLequY=
